[package]
name = "tsuki"
version = "0.1.0"
authors = ["lqdev <liquidekgaming@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "tsuki-frontend",
  "tsuki-backend-llvm",
]

[dependencies]
tsuki-frontend = { path = "tsuki-frontend" }
tsuki-backend-llvm = { path = "tsuki-backend-llvm" }
